
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const worlds=[
{id:'objetos',title:'Laboratório dos Objetos',desc:'Classificação, materiais, texturas e matéria-prima.',img:'objetos'},
{id:'recursos',title:'Guardiões da Natureza',desc:'Recursos naturais, extrativismo, agricultura e pecuária.',img:'recursos'},
{id:'reciclagem',title:'Esquadrão Sustentável',desc:'3Rs, coleta seletiva e uso consciente.',img:'reciclagem'},
{id:'corpo',title:'Viagem pelo Corpo',desc:'Partes, órgãos, ossos, músculos, acessibilidade e fases da vida.',img:'corpo'},
{id:'sentidos',title:'Central dos Sentidos',desc:'Visão, audição, olfato, paladar e tato.',img:'sentidos'},
{id:'higiene',title:'Clube da Saúde',desc:'Alimentação, higiene corporal, bucal e do ambiente.',img:'higiene'}];
let bank=[],session=[],at=0,hits=0,currentText='',selected=null,voiceOn=localStorage.mcVoice!=='0';
let data=JSON.parse(localStorage.mcV3||'{"name":"","xp":0,"level":"Fácil","pin":"1234","attempts":{},"correct":{},"sessions":[],"medals":[]}');
function save(){localStorage.mcV3=JSON.stringify(data);localStorage.mcVoice=voiceOn?'1':'0';sync()}
function sync(){let lvl=Math.floor(data.xp/150)+1;$('#navName').textContent=data.name||'Explorador(a)';$('#navXP').textContent=data.xp;$('#navLevel').textContent=lvl;$('#voice').textContent=voiceOn?'🔊':'🔇'}
function show(id){['landing','home','play','parents'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id));scrollTo(0,0)}
function speak(t){if(!voiceOn||!('speechSynthesis'in window))return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang='pt-BR';u.rate=.9;speechSynthesis.speak(u)}
$('#voice').onclick=()=>{voiceOn=!voiceOn;save();if(voiceOn)speak('Leitura ativada')};$('#read').onclick=()=>speak(currentText);
fetch('questions.json').then(r=>r.json()).then(q=>{bank=q;if(data.name)home();else show('landing')}).catch(()=>{$('#landing').innerHTML='<div class="panel"><h2>Não foi possível carregar o banco de perguntas.</h2><p>Abra o website pelo endereço publicado, e não diretamente pela pasta local.</p></div>'});
$('#enter').onclick=()=>{let n=$('#name').value.trim();data.name=n||'Explorador(a)';save();home()};
function home(){show('home');$('#hello').textContent=data.name;renderWorlds();renderMedals();sync()}
$('#back').onclick=home;$('#parentsBack').onclick=home;$$('[data-level]').forEach(b=>b.onclick=()=>{data.level=b.dataset.level;save();renderWorlds()});
function renderWorlds(){$$('[data-level]').forEach(b=>b.classList.toggle('active',b.dataset.level===data.level));$('#worlds').innerHTML=worlds.map(w=>{let a=data.attempts[w.id]||0,c=data.correct[w.id]||0,p=a?Math.round(c/a*100):0;return `<button class="world" data-id="${w.id}"><img src="assets/${w.img}.jpg" alt="${w.title}"><div class="pad"><span class="tag">${data.level}</span><h3>${w.title}</h3><p>${w.desc}</p><div class="progress"><div class="bar" style="width:${p}%"></div></div><small>${a?p+'% de acertos':'Nova missão'}</small></div></button>`}).join('');$$('.world').forEach(x=>x.onclick=()=>startWorld(x.dataset.id))}
function addMedal(id){if(!data.medals.includes(id))data.medals.push(id)}
const allMedals=[['first','🚀','Primeira missão'],['xp100','⚡','100 XP'],['perfect','🏆','Missão perfeita'],['explorer','🧭','4 mundos'],['scientist','🔬','500 XP'],['master','🌟','Mestre da Ciência']];
function checkMedals(){if(data.sessions.length)addMedal('first');if(data.xp>=100)addMedal('xp100');if(data.sessions.some(s=>s.hits===s.total))addMedal('perfect');if(new Set(data.sessions.map(s=>s.world)).size>=4)addMedal('explorer');if(data.xp>=500)addMedal('scientist');if(data.xp>=1000)addMedal('master')}
function medalHTML(){return allMedals.map(m=>`<div class="medal ${data.medals.includes(m[0])?'unlocked':''}"><div class="big">${data.medals.includes(m[0])?m[1]:'🔒'}</div><b>${m[2]}</b></div>`).join('')}
function renderMedals(){checkMedals();$('#medals').innerHTML=medalHTML();save()}
function startWorld(id){let pool=bank.filter(q=>q.image===id&&q.level===data.level);session=shuffle(pool).slice(0,10);at=0;hits=0;show('play');$('#gameTitle').textContent=worlds.find(w=>w.id===id).title;renderQuestion()}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function renderQuestion(){let q=session[at];currentText=q.prompt;$('#gameBar').style.width=(at/session.length*100)+'%';$('#gameArea').innerHTML=`<img class="gameimg" src="assets/${q.image}.jpg" alt="Ilustração do tema"><span class="tag">${q.topic}</span><div class="question">${q.prompt}</div><div class="choices">${q.options.map((o,i)=>`<button class="choice" data-i="${i}">${o}</button>`).join('')}</div><div class="feedback"></div>`;speak(currentText);$$('.choice').forEach(b=>b.onclick=()=>answer(q,b))}
function answer(q,b){if($$('.choice.correct').length)return;let ok=+b.dataset.i===q.answer;let world=q.image;data.attempts[world]=(data.attempts[world]||0)+1;data.attempts[q.topic]=(data.attempts[q.topic]||0)+1;if(ok){data.correct[world]=(data.correct[world]||0)+1;data.correct[q.topic]=(data.correct[q.topic]||0)+1;data.xp+=data.level==='Fácil'?10:data.level==='Médio'?15:20;hits++;popXP(data.level==='Fácil'?10:data.level==='Médio'?15:20)}b.classList.add(ok?'correct':'wrong');$$('.choice')[q.answer].classList.add('correct');$('.feedback').innerHTML=`${ok?'🌟 Muito bem!':'💡 Vamos aprender:'} ${q.explanation}<br><br><button class="btn green" id="next">${at+1<session.length?'Próxima pergunta':'Ver resultado'}</button>`;save();$('#next').onclick=()=>{at++;at<session.length?renderQuestion():finishSession(world)}}
function popXP(n){let d=document.createElement('div');d.className='xpfloat';d.textContent='+'+n+' XP';document.body.appendChild(d);setTimeout(()=>d.remove(),1200)}
function finishSession(world){data.sessions.unshift({date:new Date().toISOString(),world,level:data.level,hits,total:session.length});data.sessions=data.sessions.slice(0,30);checkMedals();save();currentText=`Missão concluída. Você acertou ${hits} de ${session.length}.`;$('#gameBar').style.width='100%';$('#gameArea').innerHTML=`<div style="text-align:center;padding:25px"><div style="font-size:68px">${hits===session.length?'🏆':'🎉'}</div><h2>Missão concluída!</h2><p class="question">${hits} de ${session.length} acertos</p><p>Você agora tem <b>${data.xp} XP</b>.</p><button class="btn" onclick="home()">Voltar aos mundos</button></div>`;speak(currentText)}
$('#parentsBtn').onclick=()=>{show('parents');$('#lock').classList.remove('hidden');$('#dashboard').classList.add('hidden');$('#pin').value=''};$('#unlock').onclick=()=>{if($('#pin').value===data.pin){$('#lock').classList.add('hidden');$('#dashboard').classList.remove('hidden');renderDashboard()}else alert('PIN incorreto')};
function renderDashboard(){let total=Object.keys(data.attempts).filter(k=>worlds.some(w=>w.id===k)).reduce((s,k)=>s+data.attempts[k],0),correct=Object.keys(data.correct).filter(k=>worlds.some(w=>w.id===k)).reduce((s,k)=>s+data.correct[k],0),rate=total?Math.round(correct/total*100):0;$('#metrics').innerHTML=`<div class="metric"><span>XP total</span><b>${data.xp}</b></div><div class="metric"><span>Nível</span><b>${Math.floor(data.xp/150)+1}</b></div><div class="metric"><span>Perguntas</span><b>${total}</b></div><div class="metric"><span>Aproveitamento</span><b>${rate}%</b></div>`;let topics=[...new Set(bank.map(q=>q.topic))];$('#topicReport').innerHTML=`<table><thead><tr><th>Tema</th><th>Acertos</th><th>Tentativas</th><th>Resultado</th></tr></thead><tbody>${topics.map(t=>{let a=data.attempts[t]||0,c=data.correct[t]||0,p=a?Math.round(c/a*100):0;return `<tr><td>${t}</td><td>${c}</td><td>${a}</td><td>${p}%</td></tr>`}).join('')}</tbody></table>`;$('#parentMedals').innerHTML=medalHTML()}
$('#csv').onclick=()=>{let topics=[...new Set(bank.map(q=>q.topic))],lines=['Tema;Acertos;Tentativas;Aproveitamento'];topics.forEach(t=>{let a=data.attempts[t]||0,c=data.correct[t]||0;lines.push(`${t};${c};${a};${a?Math.round(c/a*100):0}%`)});let u=URL.createObjectURL(new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv'})),a=document.createElement('a');a.href=u;a.download='relatorio-missao-ciencias.csv';a.click();URL.revokeObjectURL(u)};
$('#changePin').onclick=()=>{let p=prompt('Novo PIN numérico (4 a 6 dígitos):');if(/^\d{4,6}$/.test(p)){data.pin=p;save();alert('PIN alterado.')}else if(p!==null)alert('Use de 4 a 6 números.')};$('#reset').onclick=()=>{if(confirm('Apagar todo o progresso deste perfil?')){data={name:data.name,xp:0,level:'Fácil',pin:data.pin,attempts:{},correct:{},sessions:[],medals:[]};save();renderDashboard()}};
sync();
